Models:
    DartsTCNModel.model_name: Config_TCN
    DartsTCNModel.input_chunk_length: 7
    DartsTCNModel.output_chunk_length: 5
    DartsTCNModel.kernel_size: 3
    DartsTCNModel.num_filters: 32
    DartsTCNModel.dilation_base: 2
    DartsTCNModel.num_layers: 3
    DartsTCNModel.dropout: 0.1
    DartsTCNModel.weight_norm: True
    DartsTCNModel.n_epochs: 1
    DartsTCNModel.batch_size: 2
    DartsTCNModel.lr: 0.001
    DartsTCNModel.random_state: null
    DartsTCNModel.likelihood: QuantileRegression
    DartsTCNModel.quantiles: [0.01, 0.5, 0.99]
    DartsTCNModel.rolling_window: True
    DartsTCNModel.forecast_horizon: 5

DataSources: 
  BaltBestAggregatedAPIData:
    roles:
      TARGET: [q_hca]
      KNOWN: [temperature_outdoor_avg]
      OBSERVED: ['temperature_1_max', 'temperature_2_max','temperature_room_avg']

DataProvider:
    splits: [0.33, 0.66]
    
Metrics:
  DimwiseAggregatedQuantileLoss:
    axes: [OFFSET]
  DimwiseAggregatedMetric:
    axes: [OFFSET]

ClearML:
  task:
    project_name: ForeSightNEXT/BaltBest
    task_name: Forcateri Pipeline Test